/*consulta irá retornar protocolos com o 
Texto de solicitação, assunto, Data de abertura
*/

SELECT 
HX.CODATENDIMENTO,
CASE 
WHEN SM.IDPERLET = 3 THEN 'CM - 2019'
WHEN SM.IDPERLET = 4 THEN 'DEO -2019'
END UNIDADE,

HX.RAALUNO,
SM.CODTURMA,
HX.NOME ALUNO,
HX.ASSUNTOOC,
HX.ABERTURA,
HS.TEXTOSOLICITACAO

FROM HATENDIMENTOBASE HA
INNER JOIN HATENDIMENTOEXT HX ON (HA.CODATENDIMENTO = HX.CODATENDIMENTO)
INNER JOIN HSOLICITACAO HS ON (HA.CODATENDIMENTO = HS.CODATENDIMENTO)
INNER JOIN SMATRICPL SM ON (HX.RAALUNO = SM.RA)

WHERE HA.CODGRUPOATENDIMENTO = 3
AND HA.CODTIPOATENDIMENTO = 36
AND SM.IDPERLET IN (3,4)
AND SM.CODTURMA LIKE ('E%')

ORDER BY SM.IDPERLET,SM.CODTURMA  DESC