SELECT 
SA.RA,
PP.NOME ALUNO,
ST.DESCRICAO STATUS,
PP.TELEFONE1,
PP.TELEFONE2,
PP.TELEFONE3,
PP.EMAIL
FROM
SMATRICPL SM
INNER JOIN SALUNO SA ON (SM.CODCOLIGADA = SA.CODCOLIGADA AND SM.RA =SA.RA)
INNER JOIN PPESSOA PP ON  (SA.CODPESSOA = PP.CODIGO)
INNER JOIN SSTATUS ST ON (ST.CODSTATUS = SM.CODSTATUS)
where 
SM.CODSTATUS in (20,21)  /*colocar codigo status que deseja filtrar*/
 AND SA.RA LIKE ('2020%')   /*coloquei 2020% pois é a mascara para novatos ano 2020*/
ORDER BY ST.DESCRICAO,PP.NOME